version: "3.8"

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres:10
    restart: always
    volumes:
      - .dbdata:/var/lib/postgresql
    ports:
      - 5435:5432
