version: "3.8"

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:5000
    volumes:
      - /opt/prometheus/prometheus.yml:/usr/src/app/prometheus.yml
    depends_on:
      - db

  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - prom-db:/var/lib/postgresql
    ports:
      - 5435:5432

volumes: 
  prom-db:
